version: '3.4'
services:
  bds:
    image: itzg/minecraft-bedrock-server
    container_name: bedrock_server
    environment:
      EULA: "TRUE"
      SERVER_NAME: world230109
      LEVEL_NAME: 2023-01-09
      GAMEMODE: survival
      DIFFICULTY: normal
      LEVEL_SEED: 9008355401877120259
      OPS: 2535449079439635
    ports:
      - "19132:19132/udp"
    volumes:
      - /opt/bedrock/server:/data
    stdin_open: true
    tty: true

  backup:
    image: kaiede/minecraft-bedrock-backup
    container_name: minecraft_backup
    restart: always
    depends_on:
      - "bds"
    environment:
      TZ: "Asia/Tokyo"
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/bedrock/backups:/backups
      - /opt/bedrock/server:/server