version: "3"

services:
  # Application
  mc-vanilla:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: 2G
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
    tty: true
    stdin_open: true
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G # environmentの1.25倍がベター

  # Backup
  backup:
    image: itzg/mc-backup
    depends_on:
      - mc-vanilla
    volumes:
      - ./data:/data:ro
      - ./mc-backups:/backups
      - /etc/timezone:/etc/timezone:ro
    network_mode: "service:mc-vanilla"
